eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
